### PR TITLE
Added proxy support to client

### PR DESCRIPTION
**Pull request by mnashmi**
Proxies are not a supported param by stream_socket_client() and is the http.proxy option is completely ignored. php.net/manual/en/context.socket.php

The change will first connect to a tcp proxy, issue the CONNECT command to the host, and then use the proxy to relay any data to the WebSocket.

### CODE REVIEW

**Comment by arthurkushman** [comment]
Thank u, can u make a new PR to develop branch instead of master, so we can work more separately on this feature?

**Comment by arthurkushman** [comment]
The request  feature is good, we just need to work it and set all things up to provide more compatible code with the code-base.

**Comment by mnashmi** [comment]
changes have been made

**Comment by arthurkushman** [comment]
Good work - thx

**Pull request merged**
